kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
    app: ecommerce
    version: {{.Chart.AppVersion}}
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres-pv