kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: django-static-pvc
  namespace: django-project
  labels:
    type: local
    app: sample
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  volumeName: django-static-pv