apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: django-project
  labels:
    app: sample-service
spec:
  selector:
    app: sample
  ports:
    - port: 5000
      targetPort: 5000

